### ISSUE TITLE
(virtualbox-guest-additions-guest.install) Outdated

### ISSUE THREAD

**Issue by adamtbeames** [pauby/ChocoPackages#150] opened 2022-08-21 08:55 UTC
### Checklist

- [X] I have checked the [moderation queue](https://community.chocolatey.org/packages?q=&moderatorQueue=true&moderationStatus=all-statuses&prerelease=false&sortOrder=package-download-count) and no new version has been submitted (only visible when logged in), or a version has been submitted but has failed the automated checks.

- [X] The new version is a stable release. Pre-release versions will not be added.
- [X] There are no existing [bug](https://github.com/pauby/ChocoPackages/issues?q=is%3Aissue+is%3Aopen+label%3Abug) or [outdated](https://github.com/pauby/ChocoPackages/issues?q=is%3Aissue+is%3Aopen+label%3Aoutdated) issues.
- [X] The new version has a Windows binary (EXE or MSI installer, Zip or other archive, etc).

### New Software Version

6.1.36

### Download location

https://download.virtualbox.org/virtualbox/6.1.36/Oracle_VM_VirtualBox_Extension_Pack-6.1.36a-152435.vbox-extpack

### Package Page

https://community.chocolatey.org/packages/virtualbox-guest-additions-guest.install

**Comment by pauby** [comment] 2022-08-22 10:34
This version is actually available but has been unlisted as it was causing issues. 

![image](https://user-images.githubusercontent.com/12760779/185901217-0612bffd-8e52-4b3f-b1c4-492aff079b4e.png)

Having said that, last week I took a look at it myself and could not reproduce the issue. So, I've gone back to the person who reported it and asked them to try again. Once I have an answer, I'll be able to move forward with this.

**Comment by pauby** [comment] 2022-09-03 14:02
Version 6.1.38 is now approved and available so I'm going to go ahead and close this.

**Closed** 2022-09-03 14:02 UTC
Labels: invalid / cant reproduce / wontfix, waiting on user
