### ISSUE TITLE
(syncthing) v1.18.1 fails - Cannot convert 'System.Object[]' to the type 'System.String' required by parameter 'FileFullPath64'

### ISSUE THREAD

**Issue by laurinkeithdavis** [pauby/ChocoPackages#88] opened 2021-08-04 12:08 UTC
syncthing v1.18.1 [Approved]
syncthing package files upgrade completed. Performing other installation steps.
ERROR: Cannot convert 'System.Object[]' to the type 'System.String' required by parameter 'FileFullPath64'. Specified method is not supported.
The upgrade of syncthing was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\syncthing\tools\chocolateyInstall.ps1'.
 See log for details.

**Comment by pauby** [comment] 2021-12-16 14:47
Thanks for letting me know about this. I'll take a look (I know this is old, apologies).

**Comment by pauby** [comment] 2022-03-08 18:16
I can't reproduce this issue.

```
PS C:\Users\WDAGUtilityAccount> choco install syncthing
Chocolatey v0.12.1
Installing the following packages:
syncthing
By installing, you accept licenses for the packages.
Progress: Downloading syncthing 1.19.1... 100%

syncthing v1.19.1 [Approved]
syncthing package files install completed. Performing other installation steps.
Extracting 64-bit C:\ProgramData\chocolatey\lib\syncthing\tools\syncthing-windows-amd64-v1.19.1_x64.zip to C:\ProgramData\chocolatey\lib\syncthing\tools...
C:\ProgramData\chocolatey\lib\syncthing\tools
 ShimGen has successfully created a shim for syncthing.exe
 The install of syncthing was successful.
  Software installed to 'C:\ProgramData\chocolatey\lib\syncthing\tools'

Chocolatey installed 1/1 packages.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
```

**Comment by pauby** [comment] 2022-03-08 18:17
Wait a second. That's an upgrade. Let me try that again.

**Comment by pauby** [comment] 2022-03-08 18:19
Still can't reproduce this:

```
PS C:\Users\WDAGUtilityAccount> choco install syncthing --version 1.18.5
Chocolatey v0.12.1
Installing the following packages:
syncthing
By installing, you accept licenses for the packages.
Progress: Downloading syncthing 1.18.5... 100%

syncthing v1.18.5 [Approved]
syncthing package files install completed. Performing other installation steps.
Extracting 64-bit C:\ProgramData\chocolatey\lib\syncthing\tools\syncthing-windows-amd64-v1.18.5_x64.zip to C:\ProgramData\chocolatey\lib\syncthing\tools...
C:\ProgramData\chocolatey\lib\syncthing\tools
 ShimGen has successfully created a shim for syncthing.exe
 The install of syncthing was successful.
  Software installed to 'C:\ProgramData\chocolatey\lib\syncthing\tools'

Chocolatey installed 1/1 packages.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
PS C:\Users\WDAGUtilityAccount> choco upgrade syncthing
Chocolatey v0.12.1
Upgrading the following packages:
syncthing
By upgrading, you accept licenses for the packages.

You have syncthing v1.18.5 installed. Version 1.19.1 is available based on your source(s).
Progress: Downloading syncthing 1.19.1... 100%

syncthing v1.19.1 [Approved]
syncthing package files upgrade completed. Performing other installation steps.
Extracting 64-bit C:\ProgramData\chocolatey\lib\syncthing\tools\syncthing-windows-amd64-v1.19.1_x64.zip to C:\ProgramData\chocolatey\lib\syncthing\tools...
C:\ProgramData\chocolatey\lib\syncthing\tools
 ShimGen has successfully created a shim for syncthing.exe
 ShimGen has successfully created a shim for syncthing.exe
 The upgrade of syncthing was successful.
  Software installed to 'C:\ProgramData\chocolatey\lib\syncthing\tools'

Chocolatey upgraded 1/1 packages.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
```

**Comment by laurin1** [comment] 2022-03-08 19:10
I uninstalled and reinstalled and has not happened again...yet.

**Comment by pauby** [comment] 2022-04-23 14:57
As this issue can't be reproduced I'm going to go ahead and close it.

**Closed by pauby** 2022-04-23 14:57 UTC
Labels: bug, waiting on user
